version: 1
project:
  authors:
    - id: student
      name: Maciej Topyla
      affiliations:
        - tud

  contributors:
    - id: supervisor-1
      name: Freek Pols
      affiliations:
        - tud
    - id: committee-1
      name: Prof. Dr. C. Examiner
      affiliations:
        - tud
    - id: committee-2
      name: Dr. D. Examiner
      affiliations:
        - tud

  affiliations:
    - id: tud
      institution: Delft University of Technology
      #city: Delft
      #country: Netherlands
