version: 1
project:
  options:
    thesis_degree: Master of Science
    thesis_program: Applied Physics
    thesis_faculty: Faculty of Applied Sciences
    thesis_institution: Delft University of Technology
    thesis_defense_date: Friday June 19, 2026 at 10:00