version: 1
project:
  authors:
    - id: student
      name: Maciej Topyla
      affiliations:
        - tud
    - id: advisor
      name: Freek Pols
      affiliations:
        - tud

  affiliations:
    - id: tud
      institution: Delft University of Technology
      #city: Delft
      #country: Netherlands

  options:
    thesis_supervisors: |
      Prof. Dr. A. Example
      Dr. B. Example
    thesis_committee: |
      Prof. Dr. C. Examiner
      Dr. D. Examiner