version: 1
project:
  downloads:
    - id: thesis-pdf
  exports:
    - id: thesis-pdf
      format: typst
      template: ../
      output: ./exports/thesis_typst.pdf
      show_cover_full: true
      show_title_page: true
      show_title_page_image: false
      show_contributor_affiliations: true
      show_toc: true
      show_list_of_figures: false
      show_list_of_tables: false
      frontmatter_numbering: roman
      mainmatter_numbering: arabic

# page layout and styling      
      paper_size: a4
      margin_top_cm: 2.5
      margin_bottom_cm: 2.5
      margin_left_cm: 3.0
      margin_right_cm: 2.0
      font_body: Libertinus Serif
      font_mono: Consolas
      font_size_pt: 11
      line_spacing_em: 1
      
      toc_depth: 3
      logo: config/assets/brand/logo.svg

      # Cover variant: simple | graphical | custom
      cover_page_variant: graphical
      cover_background_image: config/assets/figures/cover.jpg
      cover_title_box_opacity_pct: 55
      
      # Title-page variant: simple | formal | custom
      title_page_variant: "formal"
      title_page_image: config/assets/figures/cover.jpg
      title_page_image_anchor: bottom
      title_page_image_width_cm: 3
      title_page_image_dx_cm: 0
      title_page_image_dy_cm: -3.0
